version: "3.9"
services:
  postgres:
    container_name: billy-postgres
    image: postgres
    environment:
      POSTGRES_DB: "billy"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
